# Generated by Django 5.2.1 on 2025-05-31 17:38

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("yonetim", "0005_alter_kullanici_username_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kullanici",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
        migrations.AddConstraint(
            model_name="kullanici",
            constraint=models.UniqueConstraint(
                fields=("username", "site_kodu"),
                name="unique_username_per_site",
                violation_error_message="Bu kullanıcı adı bu site için zaten kullanılıyor.",
            ),
        ),
    ]
